apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-perros
spec:
  selector:
    matchLabels:
      app: pod1 
  template:
    metadata:
      labels:
        app: pod1
    spec:
      containers:
      - name: container1
        image: edgardovefe/angularapps:perros
