apiVersion: v1 
kind: Service #TipoDeObjeto
metadata:
  name: appserviceyaml #nombre del servicio
spec: #configuracion del servicio
  selector: #Aqui se indica que pods serán expuestos
    app: application-pod

  ports: #Puertos a exponer
    - name: app
      port: 8080 #Puerto externo
      targetPort: 8080 #puerto de la aplicación

  type: LoadBalancer #Tipo de exposición 
  



