kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: role-developer
rules:
  - apiGroups: [""]
    resources: ["namespaces","pods"]
    verbs: ["get", "watch", "list"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: binding-developers
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: role-developer
subjects:
- kind: Group
  name: "developers"
  apiGroup: rbac.authorization.k8s.io
